name: package-data-example
channels:
  - conda-forge
  - defaults
  - intake

dependencies:
  - python
  - pip
  - intake
  - intake-parquet
  - dask
  - pandas=1.5.3
  - panel
  - tqdm
  - hvplot
  - colorcet
  - s3fs
  - anaconda-package-data
  - python-snappy
  - jupyter
  - notebook
  - pip:
    - jupyter-panel-proxy
